# Build website
[build]
command = "yarn run build"
publish = "modules/website/out"

[build.environment]
NETLIFY_NEXT_PLUGIN_SKIP = "true"

# Custom 404
[[redirects]]
from = "/*"
to = "/404/"
status = 404

# Terry Pratchett homage
[[headers]]
for = "/*"
[headers.values]
X-Clacks-Overhead = "GNU Terry Pratchett"
