import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';

import localFont from 'next/font/local';

// Font files can be colocated inside of `pages`
const brefFont = localFont({
  src: './fonts/ITC_Lubalin_Graph_Book_Regular.otf',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${brefFont.className} antialiased`}>{children}</body>
    </html>
  );
}
